-- MySQL Script generated by MySQL Workbench
-- 11/07/16 20:04:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema smartparking
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `smartparking` ;

-- -----------------------------------------------------
-- Schema smartparking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartparking` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `smartparking` ;

-- -----------------------------------------------------
-- Table `smartparking`.`parking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartparking`.`parking` (
  `idparking` INT NOT NULL,
  `min_time` TIME(3) NOT NULL,
  `max_time` TIME(3) NOT NULL,
  `average_time` TIME(3) NOT NULL,
  PRIMARY KEY (`idparking`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartparking`.`plaque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartparking`.`plaque` (
  `idplaque` VARCHAR(45) NOT NULL,
  `file` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idplaque`),
  UNIQUE INDEX `file` (`file` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartparking`.`history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartparking`.`history` (
  `idhistory` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parking_idparking` INT NOT NULL,
  `plaque_idplaque` VARCHAR(45) NOT NULL,
  `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NULL DEFAULT NULL,
  `time_parking` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`idhistory`, `parking_idparking`, `plaque_idplaque`),
  INDEX `fk_history_parking_idx` (`parking_idparking` ASC),
  INDEX `fk_history_plaque_idx` (`plaque_idplaque` ASC),
  CONSTRAINT `fk_history_parking`
    FOREIGN KEY (`parking_idparking`)
    REFERENCES `smartparking`.`parking` (`idparking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_history_plaque`
    FOREIGN KEY (`plaque_idplaque`)
    REFERENCES `smartparking`.`plaque` (`idplaque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartparking`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartparking`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(128) NOT NULL,
  `hash_password` VARCHAR(128) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
