-- MySQL Script generated by MySQL Workbench
-- 11/22/16 16:45:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema smartparking
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `smartparking` ;

-- -----------------------------------------------------
-- Schema smartparking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartparking` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `smartparking` ;

-- -----------------------------------------------------
-- Table `smartparking`.`parking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartparking`.`parking` (
  `id_parking` INT NOT NULL,
  `min_time` TIME(3) NULL,
  `max_time` TIME(3) NULL DEFAULT NULL,
  `average_time` TIME(3) NULL DEFAULT NULL,
  `current_status` VARCHAR(15) NOT NULL DEFAULT 'Available',
  PRIMARY KEY (`id_parking`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartparking`.`record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartparking`.`record` (
  `id_record` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parking_id_parking` INT NOT NULL,
  `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NULL DEFAULT NULL,
  `time_parking` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_record`, `parking_id_parking`),
  INDEX `fk_record_parking_idx` (`parking_id_parking` ASC),
  CONSTRAINT `fk_record_parking`
    FOREIGN KEY (`parking_id_parking`)
    REFERENCES `smartparking`.`parking` (`id_parking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartparking`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartparking`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password_hash` VARCHAR(45) NOT NULL,
  `auth_key` VARCHAR(32) NOT NULL,
  `access_token` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
